baseURL = "https://jocobtt.github.io/"
languageCode = "en-us"
title = "Jacob's Tech Tangents"
theme = "kube"
description = "Website for me to keep some blogs and other stuff"
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  github = "jocobtt" # add your github profile name
  twitter = "jbrazzy-1" # add your twitter profile
  email = "jacob.braswell00@gmail.com"

[[menu.main]]
    name = "Docs"
    weight = -100
    url = "/docs/"
[[menu.main]]
    name = "Blog"
    weight = -100
    url = "/posts/"
[[menu.main]]
    name = "About"
    weight = -100 
    url = "/about/"
[[menu.main]]
    name = "Faq"
    weight = -100
    url = "/faq/"
#[[menu.main]]
#    name = "Resume"
#    weight = -100
#    url = "/resume"


#[languages]
# [languages.jp]
#   languagename = "Japanese"
#   title = ”ジェコブ”
#
#   [languages.jp.params]
#   author = "ジェコブ"
#   info = "データサイエンティスト"
#   description = "Just a guy who likes to code, AI/ML, Kubernetes, python and running"
#   keywords = "blog,developer,personal"
#
#   [languages.jp.menu]
#
#   [[languages.en.menu.main]]
#   name = "About"
#   weight = 1.0
#   url = "/about/"




#[sitemap]
#ChangeFreq = ""
#Filename = "sitemap.xml"
#Priority = "-1"


# https://dev.to/dgavlock/creating-a-hugo-site-on-github-pages-3cjo - look at this for how to add different languages 
# https://gohugo.io/getting-started/configuration/

