baseURL = "https://jocobtt.github.io/"
languageCode = "en-us"
title = "Jacob's Tech Tangents"
theme = "kube"
description = "Website for me to keep some blogs and other stuff"
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  github = "jocobtt" # add your github profile name
  twitter = "jbrazzy-1" # add your twitter profile
  email = "jacob.braswell00@gmail.com"

[[menu.main]]
    name = "Docs"
    weight = -100
    url = "/docs/"
[[menu.main]]
    name = "Blog"
    weight = -100
    url = "/posts/"
[[menu.main]]
    name = "About"
    weight = -100 
    url = "/about/"
[[menu.main]]
    name = "Faq"
    weight = -100
    url = "/faq/"
